spring:
  #------ required for batch---
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  #------ required for batch---
  application:
    name: sample-batch-app
  datasource:
    url: jdbc:postgresql://localhost:5332/sample_batch
    username: demo_dev
    password: demo_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect